from __future__ import annotations


def format_pr_comment(
    changed_function: str,
    impact_score: int,
    impact_level: str,
    affected_components: list[str],
    component_levels: dict[str, str],
    explanation: str,
    impact_paths: list[list[str]],
    recommended_tests: list[str],
) -> str:
    lines: list[str] = []
    lines.append("🧬 **CODEGENOME IMPACT REPORT**")
    lines.append("")
    lines.append(f"**Impact Score:** {impact_score}/100")
    lines.append(f"**Risk:** {impact_level}")
    lines.append("")
    lines.append("**Changed:**")
    lines.append(f"- `{changed_function}`")
    lines.append("")
    lines.append("**Potentially affected:**")
    for comp in affected_components:
        level = component_levels.get(comp, "LOW")
        lines.append(f"- {comp} — {level}")
    lines.append("")
    lines.append("**Why:**")
    lines.append("")
    lines.append(explanation)
    lines.append("")
    if impact_paths:
        lines.append("**Impact paths:**")
        for path in impact_paths[:5]:
            lines.append("- " + " → ".join(f"`{p}`" for p in path))
        lines.append("")
    lines.append("**Recommended Tests:**")
    for test in recommended_tests[:8]:
        lines.append(f"- ✓ {test}")
    if len(recommended_tests) > 8:
        lines.append(f"- ○ {recommended_tests[8]}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by CodeGenome — deterministic static analysis*")
    return "\n".join(lines)


__all__ = ["format_pr_comment"]
